name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install --upgrade pip wheel
      - run: pip install bandit black codespell flake8 flake8-comprehensions isort
                         mypy pytest pyupgrade safety  # flake8-bugbear
      - run: bandit --recursive --skip B101 .  # B101 is assert statements
      - run: black --check . || true
      - run: codespell
      - run: flake8 . --count --max-complexity=18 --max-line-length=88 --show-source --statistics
      - run: isort --check-only --profile black . || true
      - run: pip install -r requirements.txt
      - run: mkdir --parents --verbose .mypy_cache
      - run: mypy --ignore-missing-imports --install-types --non-interactive . || true
      - run: pytest . || pytest --doctest-modules . || true
      - run: pytest run_tests.py --cov flake8_builtins --cov-report term-missing
      - run: coveralls
      - run: shopt -s globstar && pyupgrade --py36-plus **/*.py || true
      - run: safety check
